import { type FC, useCallback, useMemo } from 'react'
import { Report } from './Report'
import { filesToDataSource } from './helpers/summary'
import { cwdBaseName, toRelativePath } from './paths'
import type { FileCoverageData, FileDataResponse, ReportAppProps } from './types'
import { useHashPath } from './useHashPath'

const emptyFileCoverage: FileCoverageData = {
  path: '',
  statementMap: {},
  fnMap: {},
  branchMap: {},
  s: {},
  f: {},
  b: {},
}

function npmPackageVersionUrl(packageName: string, packageVersion: string): string {
  return `https://www.npmjs.com/package/${packageName}/v/${encodeURIComponent(packageVersion)}`
}

export const ReportApp: FC<ReportAppProps> = ({
  files = [],
  instrumentCwd,
  generatedAt,
  name,
  defaultValue = '',
  packageName,
  packageVersion,
  height = 'calc(100vh - 16px)',
  showFooter = true,
}) => {
  const [value, setValue] = useHashPath(defaultValue)

  const relativeFiles = useMemo(() => {
    return files.map((item) => ({
      ...item,
      path: toRelativePath(item.path, instrumentCwd),
    }))
  }, [files, instrumentCwd])

  const dataSource = useMemo(() => filesToDataSource(relativeFiles), [relativeFiles])
  const reportName = name ?? cwdBaseName(instrumentCwd)

  const onSelect = useCallback(
    (val: string): Promise<FileDataResponse> => {
      setValue(val)
      const file = relativeFiles.find((item) => item.path === val)
      if (file === undefined) {
        return Promise.resolve({
          fileCoverage: emptyFileCoverage,
          fileContent: '',
        })
      }
      return Promise.resolve({
        fileCoverage: file,
        fileContent: file.source,
      })
    },
    [relativeFiles, setValue],
  )

  return (
    <div
      style={{
        height,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div style={{ flex: 1, minHeight: 0 }}>
        <Report name={reportName} value={value} dataSource={dataSource} onSelect={onSelect} />
      </div>
      {showFooter ? (
        <div
          style={{
            textAlign: 'center',
            fontSize: '12px',
            color: 'rgba(0,0,0,0.5)',
          }}
        >
          Code coverage generated by{' '}
          <a
            href="https://github.com/canyon-project/canyon"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#0074D9', textDecoration: 'underline' }}
          >
            canyonjs
          </a>
          {packageName && packageVersion ? (
            <>
              {' '}
              ·{' '}
              <a
                href={npmPackageVersionUrl(packageName, packageVersion)}
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: '#0074D9', textDecoration: 'underline' }}
              >
                {packageName} v{packageVersion}
              </a>
            </>
          ) : null}{' '}
          at {generatedAt ?? new Date().toISOString()}
        </div>
      ) : null}
    </div>
  )
}

export default ReportApp
